[build]
  command = "npm run netlify-build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  CI = "false"
  ESBUILD_SKIP_BINARY_VERSION_CHECK = "1"

[context.production]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.branch-deploy]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.deploy-preview]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
