[build]
  publish = "dist"
  command = "npm install --platform=linux --arch=x64 && npm run build"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.8.1"
  ROLLUP_SKIP_PLATFORM_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
