[build]
  publish = "dist"
  command = "npm ci --ignore-scripts && npm run build"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.8.1"
  NPM_FLAGS = "--no-optional --no-audit"
  CI = "true"
  ROLLUP_SKIP_PLATFORM_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
