[build]
  publish = "dist"
  command = "npm install --no-optional && npm run build"

[build.environment]
  NODE_VERSION = "18"
  ROLLUP_SKIP_PLATFORM_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
