[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --no-audit --no-fund"
  ROLLUP_SKIP_PLATFORM_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
